# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-25 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0021_auto_20190422_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary_user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Temporary user')),
                ('message', models.TextField(verbose_name='Message')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of message')),
                ('was_read', models.BooleanField(default=False, verbose_name='Was read')),
                ('reading_date', models.DateTimeField(blank=True, null=True, verbose_name='Reading date')),
                ('receiver_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('subject_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.Advertisement', verbose_name='Dialog')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['pub_date'],
            },
        ),
    ]
