# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-06 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190427_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='was_read',
            new_name='is_readed',
        ),
        migrations.AddField(
            model_name='chat',
            name='last_send_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_send_message', to='chat.Message'),
        ),
    ]
