# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-20 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190514_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
    ]
