# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 17:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='locations_user',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='locations'),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='phone_number_user',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number user'),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='username',
            field=models.CharField(blank=True, max_length=254, verbose_name='username'),
        ),
    ]
