# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181209_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomuser',
            name='locations_user',
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='location_user',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='location'),
        ),
    ]
