# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-13 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181211_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
