# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-13 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mycustomuser_is_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomuser',
            name='is_admin',
        ),
    ]
