# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_mycustomuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='moderator'),
        ),
    ]
