# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=utils.get_file_path, verbose_name='фото'),
        ),
    ]
