# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementmessage',
            name='text',
        ),
        migrations.AddField(
            model_name='advertisementmessage',
            name='text_massage',
            field=models.TextField(default='', max_length=450, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='phone_author',
            field=models.IntegerField(default=380),
        ),
        migrations.AlterField(
            model_name='advertisementmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
