# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Advertisment', 'verbose_name_plural': 'Advertisments'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location_author',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='location'),
        ),
    ]
