# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20181213_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementfollowing',
            options={'verbose_name': 'Advertisment is following', 'verbose_name_plural': 'Advertisments are following'},
        ),
        migrations.AlterModelOptions(
            name='advertisementimage',
            options={'verbose_name': 'Image of Advertisment', 'verbose_name_plural': 'Images of Advertisments'},
        ),
        migrations.AlterModelOptions(
            name='advertisementmessage',
            options={'verbose_name': 'Advertisment massage', 'verbose_name_plural': 'Advertisment massages'},
        ),
        migrations.RenameField(
            model_name='advertisementfollowing',
            old_name='publication',
            new_name='advertisement',
        ),
        migrations.RenameField(
            model_name='advertisementimage',
            old_name='advertisment',
            new_name='advertisement',
        ),
        migrations.AlterField(
            model_name='advertisementmessage',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.Advertisement'),
        ),
    ]
