# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20180416_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(height_field=640, upload_to=utils.get_file_path, width_field=480),
        ),
    ]
