# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_auto_20180418_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone_author',
            field=models.IntegerField(max_length=15),
        ),
    ]
