# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_auto_20180419_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to=utils.get_file_path),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='phone_author',
            field=models.IntegerField(),
        ),
    ]
