# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_auto_20181214_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(default='', verbose_name='Description advertisment'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='location_author',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='location'),
        ),
    ]
