# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_auto_20180420_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_file_path),
        ),
    ]
