# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_auto_20181219_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
