# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_auto_20180422_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-added']},
        ),
    ]
