# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_auto_20180423_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
