# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-05 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_auto_20180425_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-added'], 'verbose_name': 'advertisement', 'verbose_name_plural': 'advertisements'},
        ),
    ]
