# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_auto_20190128_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisements.Advertisement'),
        ),
    ]
