# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-18 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_auto_20180505_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='body',
            field=models.TextField(max_length=500, verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.get_file_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='phone_author',
            field=models.IntegerField(verbose_name='Телефон автора'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type_equipment',
            field=models.CharField(max_length=255, verbose_name='Тип оборудования'),
        ),
    ]
