# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-10 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0012_auto_20190302_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='hit_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Hit count'),
        ),
    ]
