# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-13 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0013_advertisement_hit_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('hits_counter', models.PositiveIntegerField(default=0, verbose_name='Hit count')),
            ],
            options={
                'verbose_name': 'Views of advertisment',
                'verbose_name_plural': 'Views of advertisments',
            },
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='hit_counter',
        ),
        migrations.AddField(
            model_name='pagehit',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='advertisements.Advertisement'),
        ),
        migrations.AddField(
            model_name='pagehit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
