# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0014_auto_20190313_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagehit',
            name='user',
        ),
        migrations.AlterField(
            model_name='pagehit',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='advertisements.Advertisement'),
        ),
        migrations.AlterField(
            model_name='pagehit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
