# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0016_auto_20190409_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementfollowing',
            options={'verbose_name': 'Advertisement is following', 'verbose_name_plural': 'Advertisements are following'},
        ),
        migrations.AlterModelOptions(
            name='advertisementimage',
            options={'verbose_name': 'Image of Advertisement', 'verbose_name_plural': 'Images of Advertisements'},
        ),
        migrations.AlterModelOptions(
            name='advertisementmessage',
            options={'verbose_name': 'Advertisement massage', 'verbose_name_plural': 'Advertisement massages'},
        ),
        migrations.AlterModelOptions(
            name='pagehit',
            options={'verbose_name': 'Views of advertisement', 'verbose_name_plural': 'Views of advertisements'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category_equipment',
            field=models.CharField(choices=[('iMac', 'iMac'), ('MacBook', 'MacBook'), ('iPad', 'iPad'), ('Monoblok', 'Monoblok'), ('iPhone', 'iPhone'), ('iPod', 'iPod'), ('MeidaBox', 'MeidaBox'), (('Apple Watch',), 'Apple Watch'), (('Accessory',), 'Accessory')], default='iPhone', max_length=25, verbose_name='Category advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(default='', verbose_name='Description advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='main_image',
            field=models.ImageField(blank=True, default='', upload_to=utils.get_file_path, verbose_name='Main image advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Price advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=utils.get_file_path, verbose_name='Image advertisement'),
        ),
    ]
