# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-22 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0020_auto_20190422_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
