# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-20 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0021_auto_20190422_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementmessage',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='advertisementmessage',
            name='author',
        ),
        migrations.DeleteModel(
            name='AdvertisementMessage',
        ),
    ]
