# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-27 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0022_auto_20190520_1725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_title', models.BooleanField(default=False, verbose_name='Checking of title')),
                ('check_description', models.BooleanField(default=False, verbose_name='Checking of description')),
                ('check_photos', models.BooleanField(default=False, verbose_name='Checking of photos')),
            ],
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sending_by_user', models.DateTimeField(auto_now=True, verbose_name='Time sending ad by user for checking')),
                ('start_moderate', models.DateTimeField(auto_now_add=True, verbose_name='Start checking')),
                ('end_moderate', models.DateTimeField(auto_now=True, null=True, verbose_name='Finished checking')),
                ('comment_to_ad', models.CharField(blank=True, default='', max_length=255, verbose_name='Comment to advertisement')),
                ('status', models.SmallIntegerField(choices=[(0, 'rejected'), (1, 'approved'), (2, 'at_work')], default=2, verbose_name='Choices status')),
                ('ad_to_moderate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_to_moderate', to='advertisements.Advertisement')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='moderation.Checklist')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Moderation of advertisements',
                'verbose_name': 'Moderation of advertisement',
            },
        ),
    ]
