# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0016_auto_20190409_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_title', models.BooleanField(default=False, verbose_name='Checking of title')),
                ('check_description', models.BooleanField(default=False, verbose_name='Checking of description')),
                ('check_photos', models.BooleanField(default=False, verbose_name='Checking of photos')),
            ],
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_moderate', models.DateTimeField(auto_now_add=True, verbose_name='Start checking')),
                ('end_moderate', models.DateTimeField(auto_now=True, verbose_name='Finished checking')),
                ('comment_to_ad', models.CharField(default='', max_length=255, verbose_name='Comment to advertisement')),
                ('status', models.SmallIntegerField(choices=[(0, 'rejected'), (1, 'approved'), (2, 'pending'), (3, 'at_work')], default='pending', editable=False, verbose_name='Choices status')),
                ('ad_to_moderate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_to_moderate', to='advertisements.Advertisement')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='moderation.Checklist')),
            ],
            options={
                'verbose_name_plural': 'Moderation of advertisements',
                'verbose_name': 'Moderation of advertisement',
            },
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.DateTimeField(auto_now_add=True)),
                ('fired', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='moderation',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.Moderator'),
        ),
    ]
