# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_moderation_time_sending_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='fired',
            field=models.DateTimeField(blank=True),
        ),
    ]
