# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_auto_20190409_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='fired',
        ),
    ]
