# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-13 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_remove_moderator_fired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='moderator',
        ),
        migrations.AlterField(
            model_name='moderation',
            name='comment_to_ad',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Comment to advertisement'),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'rejected'), (1, 'approved'), (2, 'pending'), (3, 'at_work')], default='pending', verbose_name='Choices status'),
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
