# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-14 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_auto_20190413_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='moderation.Checklist'),
        ),
    ]
