# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_auto_20190414_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='end_moderate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Finished checking'),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
