# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-14 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0007_auto_20190414_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderation',
            old_name='id',
            new_name='moderation_id',
        ),
    ]
