# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-19 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_auto_20190414_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'rejected'), (1, 'approved'), (2, 'at_work')], default=2, verbose_name='Choices status'),
        ),
    ]
